// Auth
export const AUTHORIZED_REQUEST = "AUTHORIZED_REQUEST";
export const AUTHORIZED = "AUTHORIZED";
export const NOT_AUTHORIZED = "NOT_AUTHORIZED";
export const AUTHORIZED_ERROR = "AUTHORIZED_ERROR";

// Create Room
export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS";
export const CREATE_ROOM_FAILURE = "CREATE_ROOM_FAILURE";

// Get Rooms
export const GET_ROOMS_SUCCESS = "GET_ROOMS_SUCCESS";
export const GET_ROOMS_FAILURE = "GET_ROOMS_FAILURE";

// Edit Room
export const EDIT_ROOM_SUCCESS = "EDIT_ROOM_SUCCESS";
export const EDIT_ROOM_FAILURE = "EDIT_ROOM_FAILURE";
