// Auth
export const AUTHORIZED_REQUEST = "AUTHORIZED_REQUEST";
export const AUTHORIZED_SUCCESS = "AUTHORIZED";
export const NOT_AUTHORIZED = "NOT_AUTHORIZED";
export const AUTHORIZED_ERROR = "AUTHORIZED_ERROR";

// Signup
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

// LOGIN
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

// LOGOUT
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

// Create Room
export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS";
export const CREATE_ROOM_FAILURE = "CREATE_ROOM_FAILURE";

// Get Rooms
export const GET_ROOMS_SUCCESS = "GET_ROOMS_SUCCESS";
export const GET_ROOMS_FAILURE = "GET_ROOMS_FAILURE";

// Get Room
export const GET_ROOM_REQUEST = "GET_ROOM_REQUEST";
export const GET_ROOM_SUCCESS = "GET_ROOM_SUCCESS";
export const GET_ROOM_FAILURE = "GET_ROOM_FAILURE";

// Update Room
export const UPDATE_ROOM_SUCCESS = "UPDATE_ROOM_SUCCESS";
export const UPDATE_ROOM_FAILURE = "UPDATE_ROOM_FAILURE";

// Get Photos
export const GET_PHOTOS_SUCCESS = "GET_PHOTOS_SUCCESS";

// Create Photo
export const CREATE_PHOTO_SUCCESS = "CREATE_PHOTO_SUCCESS";
export const CREATE_PHOTO_ERROR = "CREATE_PHOTO_ERROR";
